### ISSUE TITLE
Export Player Edition via direct URL

### ISSUE THREAD

**Issue by Mystikite** [benwebber/tiddlywiki-dnd#19]
Not an Issue, more a Feature Request.

It would be ideal to be able to export the player edition nightly via crontab'd curl call.
The current method requires a Button or similar action widget to trigger the export.

**Comment by benwebber** [comment]
Good idea. It's possible to pass a search filter through query parameters, but I'm not sure about triggering an action. This might only be possible using the TiddlyWiki CLI.

**Comment by benwebber** [comment]
I documented a workaround using the TiddlyWiki CLI. Scroll down to the player edition section:

https://benwebber.github.io/tiddlywiki-dnd/

**Comment by Mystikite** [comment]
Ben,
I tested this today, and it provides exactly what i was looking for!
I plan to cron a nightly export to the player edition.
Thank you so much for looking into this further, and providing a solution. 
I additionally have learned that the tiddlywiki command has utility functions, so i get to research what else it can do!
