### ISSUE TITLE
Spell Level Display Issue

### ISSUE THREAD

**Issue by lbhgh** [benwebber/tiddlywiki-dnd#8]
Found an issue when setting spell levels to anything other than 0, would render as $level.

Found adding a spaces here: 

$:/plugins/benwebber/dnd/language/Spell/DescriptionFormat/Default: $level$ $levelSuffix$ - level $school$
$:/plugins/benwebber/dnd/language/Spell/DescriptionFormat/Ritual: $level$ $levelSuffix$ - level $school$ (ritual)

Helped resolve the issue. Don't think tiddly likes having two $ next to each other, at least in ver5.1.23

PS - I FREAKING LOVE THIS PLUGIN AND YOU ARE ACE FOR MAKING IT. THANK YOU.

**Comment by benwebber** [comment]
Thanks for the bug report. I'm glad you like the plugin.

I can't reproduce this issue on 5.1.23. Could you publish a wiki with the bug somewhere I can download it and inspect it?

**Comment by lbhgh** [comment]
I made a tiddlywiki that contains the issue as the default tiddler on open - hope that helps!

[spellFail.zip](https://github.com/benwebber/tiddlywiki-dnd/files/6003294/spellFail.zip)

**Comment by benwebber** [comment]
Thanks. This is a conflict with the KaTeX plugin. The `$$` in `$level$$levelSuffix$` triggers the KaTeX parser.

Should be easy enough to fix. In the meantime, if you don't need to use LaTeX, try disabling the KaTeX plugin.

**Comment by benwebber** [comment]
Fixed. Check out version 1.2.1 on the demo page:

https://benwebber.github.io/tiddlywiki-dnd/

Version 1.2.0 added a bunch of new DM tools like character tiddlers, tiddler notes, and the ability to export a subset of the wiki for your players.
